version: "2"
services:
  app:
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      DATABASE_URL: mongo:27017

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data: